name: DevCard

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
